version: '3.8'

services:
  power-hub-frontend:
    build: .
    container_name: power-hub-frontend
    restart: unless-stopped
    ports:
      - "9010:80"
    networks:
      - bridge
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  bridge:
    driver: bridge
